const string = {

    label_splash: "great food deserves it’s own stage",
    label_onb_one: "Search and discover the best dishes suggested by foodies all over the world",
    label_onb_two: "Discover local restaurants that you never knew existed",
    label_onb_three: "Filter Dishes by Location, Cuisine's,Diet's & many more",
    label_onb_four: "Follow your friends to see what delicious food they are eating",
    label_signin: "Sign In",
    label_register: "Register",
    label_popular: 'Popular',
    label_history: 'History',
    label_window: "window",
    label_error: "error",
    label_signup: "Sign Up",
    label_facebook: "Connect with Facebook",
    label_username_signin: "Username, email or mobile",
    label_next: "Next",
    label_signup_terms: "By signing up to Grubshoots you are agreeing to our",
    label_terms: "Terms ",
    label_privacyPolicy: " Privacy Policy",
    label_firstLastName: "First and last name",
    label_email: "Email",
    label_forgotPassword: "Forgot Password",
    label_cancel: "Cancel",
    label_password: "Password",
    label_completeProfile: "Complete Your Profile",
    label_takePhoto: "Take a Photo",
    label_enterUserName: "Enter a username",
    label_enterFirstAndLastName: 'First and last name',
    label_mobileNo: 'Mobile number',
    label_cancel: 'Cancel',
    label_changePhoneNumber: "Change Phone Number?",
    label_sendCode: "Send Code",
    label_yourPhoneNumber: 'Your Phone Number',
    label_pleaseTypeYourNumber: 'Please type in your phone number',
    label_verificationCode: 'Verification Code',
    label_pleaseTypePhone: 'Please type in the verification code sent to',
    label_resendCode: 'Resend Code',
    label_submit: 'Submit',
    label_ffContacts: 'Contacts',
    label_ffFacebook: 'Facebook',
    label_ffNearby: 'Nearby',
    label_txtFindFriends: 'Find Friends on Grubshoots',
    label_btnFindFriends: 'Find Friends',
    label_enable: 'Enable',
    label_textFFContacts1: 'Check which of your phone contact',
    label_textFFContacts2: 'friends are on Grubshoots',
    label_textFFFacebook1: 'Check which of your Facebook friends are',
    label_textFFFacebook2: 'on Grubshoots',
    label_textFFNearby1: 'Find nearby friends who are on',
    label_textFFNearby2: 'Grubshoots',
    label_txtSkip: 'Skip',
    label_search: 'Type your search',
    label_searchUsername: 'Search Username',
    label_home: 'Home',
    label_feed: 'Feed',
    label_notifications: 'Notifications',
    label_profile: 'Profile',
    label_follow: 'Follow',
    label_followers:'followers',
    label_unFollow: 'Following',
    label_notFollow:'Unfollow',
    label_change: 'Change',
    label_Grid: 'Grid',
    label_list: 'List',
    label_fullName: 'Full Name',
    label_userName: 'Username',
    label_town: 'Town',
    label_editProfile: 'Edit Profile',
    label_country: 'Country',
    label_save: 'Save',
    label_miles: 'Miles',
    label_following:'following',
    label_setLocation: 'Set location',
    label_homeText: 'Tell us where you are!',
    label_homeText2: 'To generate feed based on your location, turn on',
    label_homeText3:'your location services',
    label_currentLocation: 'current location',
    label_next: 'Next',
    label_finish: 'Finish',
    label_i_want_to: 'I want to:',
    label_dish_home: '    Post a dish from home',
    label_dish_restaurant: 'Post a dish from a restaurant',
    label_dish_homemade_business: 'Post a dish from my homebased bussiness',
    label_price: 'Price',
    label_spice: 'Spice',
    label_portion_size: 'Portion Size',
    label_overall_rating: 'Overall Rating',
    label_meal: 'Meal',
    label_dietary: 'Dietary',
    label_cuisine: 'Cuisine',
    label_post_extended_note: 'That is called seasoning and is important in the care and use of cast iron to prevent rust and create a natural non-stick cooking surface.',
    label_spices: ['mild', 'medium', 'hot', 'extra hot'],
    label_portion_size_list: ['small', 'medium', 'large'],
    label_select_meal: 'Select meals',
    label_select_diets: 'Select diets',
    label_select_cuisines: 'Select cuisines',
    label_clear_all: 'Clear All',
    label_close: 'Close',
    label_tag_user: '+ Tag user',
    label_no_data_found: 'No Data found',
    label_description: 'Description',
    label_post_name: 'Dish Name',
    label_create_restaurant_profile: 'Create Restaurant Profile',
    label_liked: 'Liked',
    label_tagged: 'Tagged',
    label_viewd: 'Viewed',
    label_contact: 'Contacts',
    label_facebook_setting: 'Facebook',
    label_change_password: 'Change Password',
    label_notification_setting: 'Notification Settings',
    label_block_user: 'Blocked Users',
    label_private_account: 'Private Account',
    label_auto_save: 'Auto Save picture to Camera Roll',
    label_receive_noti: 'Receive Notifications via Email',
    label_privacy: 'Privacy Policies',
    label_termsAndConditions: 'Terms & Conditions ',
    label_contact_us: 'Contact Us',
    label_rate_us: 'Rate Us on App Store',
    label_feedback: 'Give Us Feedback',
    label_post: 'Posts',
    label_Post:'posts',
    label_invite_friend: 'Invite Friends',
    label_about: 'About',
    label_account: 'Account',
    label_logout: 'Logout',
    label_old_password: 'Old Password',
    label_new_password: 'New Password',
    label_repeat_password: 'Repeat New Password',
    label_type_search: 'Type your search',
    label_search_tab: ['Dishes', 'Restaurants', 'Users'],
    label_nearBy: 'Near By',
    label_search_town:'Search Town',
    label_turnOnLocation:'Turn on Location Services',
   
    screen: {
        screen_splash: "gs_splash",
        screen_onboarding: "gs_onboarding",
        screen_login: "gs_login",
        screen_forgotPassword: "gs_forgotpassword",
        screen_completeProfile: "gs_completeprofile",
        screen_changeMobileNumber: "gs_changemobilenumber",
        screen_verificationCode: "gs_verificationcode",
        screen_addPhoneNumber: "gs_addPhoneNumber",
        screen_home: "gs_home",
        screen_FindFriends: "gs_findFriends",
        screen_feed: 'gs_feed',
        screen_editProfile: 'gs_editProfile',
        screen_createpost: 'gs_createPost',
        screen_notification: 'gs_notification',
        screen_profile: 'gs_profile',
        screen_setLocation: 'SetLocation',
        screen_searchLocation: 'gs_searchLocation',
        screen_googlePlace: 'gs_googleplace',
        screen_postselection: 'gs_postselection',
        screen_postexpanded: 'gs_postexpanded',
        screen_post_taguser: 'gs_post_tag_user',
        screen_filter_post_image: 'gs_filterpostimage',
    },
    customComponent: {
        topBar: 'gs_home_topbar',
        roundButton: 'gs_home_round_button',
        searchTopBar: 'gs_search_topbar',
        topBarNext: 'gs_topbar_next',


    },
    customComponentId: {
        topBarId: 'gs_topbar',
        buttonId: 'gs_button',
        searchTopBarId: 'gs_searchTopBar',
        topBarNextId: 'gs_topbarNext'
    },

    app: {
        app_name: 'Grubshoots'
    },
    stackId: {
        stack_splash: "splashStack",
        stack_auth: "authStack",
        stack_landing: "landingStack",
        stack_home: "homeStack",
        stack_findFriends: "findFriends",
        stack_feed: 'feedStack',
        stack_post: 'stackPost',
        stack_notification: 'stackNotification',
        stack_profile: 'stackProfile',
        stack_main: 'stackMain'

    },
    alert: {
        buttonOk: "Ok",
        buttonCancel: "Cancel",
        buttonYes:'YES',
        butttonNo:'NO',
        ForgotPasswordSuccess: "An email has been sent at this mail Id with information about password.",
        NoUserFoundContacts: "Oops!! No Grubshoots users found from your contacts",
        NoUserFacebookFriend: "Oops!! No Grubshoots users found from your Facebook friends",
        NoUserFoundNearby: "Oops!! No Grubshoots users found nearby",
        CameraPermissionTitle: "Permission to use camera",
        CameraPermissionNote: "We need your permission to use your camera",
        LogoutMessage: 'Are you sure you want to logout?',
        comming_soon: "Coming soon..",
        locatinEnable: "Please enable location from Settings -> Grubshoots -> Location",
        contactsEnable:"Please enable contacts permission from Settings -> Grubshoots -> Contacts",
        cameraEnable:"Please enable camera permission from Settings -> Grubshoots -> Camera",
        galleryEnable:"Please enable photos permission from Settings -> Grubshoots -> Photos -> Read and Write",
        resendVerification: "Email with verification link has been sent to this emailId",
        inValidPassword:"Password must contain at least 1 upper character, 1 lower character, 1 special character, 1 number and should be minimum of 8 characters",
        inValidNewPassword:"New Password must contain at least 1 upper character, 1 lower character, 1 special character, 1 number and should be minimum of 8 characters",
        locationNotFound:"We are not able to fetch your current location. Please try again after some time."
    },

    errors: {
        error_noPassword: "Please enter password",
        errornoUserLogin: 'Please enter username, email or mobile',
        errorNumberLogin: 'Please enter valid number with country code',
        error_noUsername: "Please enter Username",
        error_validUsername: "Please enter valid Username",
        error_validPassword: "Please enter Valid Password",
        error_noFullName: "Please enter your first name & last name",
        error_validFullName: "First and last name must contain only alphabets",
        error_noEmail: "Please enter your emailId",
        error_validEmail: "Please enter valid emailId",
        error_invalidPassword: "Password should be minimum 8 characters long",
        error_firstAndLastName: "Please enter first and last name",
        error_mobileNo: "Please enter mobile no",
        error_validMobileNumber: "Please enter valid mobile number",
        error_profilePic: "Please select profile picture",
        error_network: "Please check your internet connection",
        error_noCode: "Please enter verification code",
        error_validCode: "Please enter valid verification code",
        error_resend_limit: 'Sorry your limit is exceed',
        error_noTown: 'Please enter your town',
        error_noCountry: 'Please enter your Country',
        error_select_image: "Please select image",
        error_not_tag_more_than_10: 'You can not tag more than 10 user',
        error_enter_post_name: 'Please enter dish name',
        error_enter_description: 'Please enter description',
        error_select_meals: 'Please select meals',
        error_select_diets: 'Please select diets',
        error_select_cuisines: 'Please select cuisines',
        error_noOldPassword: 'Please enter old password',
        error_noNewPassword: 'Please enter new password',
        error_noRepeatPassword: 'Please enter repeat password',
        error_noRepeatPasswordNewPassword: 'Password and confirm password must be same',
        error_noNw:'No Internet Connection'


    },

    icons: {
        icn_eye: "eye",
        icn_eyeSlash: "eye-slash"
    },
    topBarId: {
        locationTextId: "LocationId",
        chevronDownId: "ChevronDownId",
        logoutId: "logoutId",
        searchId: "searchId"

    }

};

export default string;