export const UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE';
export const UPDATE_OVERLAY_STATE = 'UPDATE_OVERLAY_STATE';
export const UPDATE_SEARCH_VIEW = 'UPDATE_SEARCH_VIEW';
export const UPDATE_PLACE_DATA = 'UPDATE_PLACE_DATA';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_SELECTED_LOCATION = "UPDATE_SELECTED_LOCATION"
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT'
export const UPDATE_FIRSTTIMESETLOCATION = "UPDATE_FIRSTTIMESETLOCATION"
export const SELECTED_POST_IMAGE = "SELECTED_POST_IMAGE"

